# Generated by Django 2.2.1 on 2019-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=50, unique=True)),
                ('cityCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=50, unique=True)),
                ('countryCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
