# Generated by Django 2.2.1 on 2019-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='countryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
