# Generated by Django 2.2.1 on 2019-05-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=130)),
                ('container_text', models.TextField()),
                ('container_location', models.CharField(choices=[('frontend', 'Frontend'), ('footer', 'Footer')], default='footer', max_length=20)),
            ],
        ),
    ]
