# Generated by Django 2.2.1 on 2019-05-06 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('streetName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('streetNumber', models.IntegerField(blank=True, default='', null=True)),
                ('postalCode', models.IntegerField(blank=True, default='', null=True)),
                ('size', models.IntegerField(blank=True, default='', null=True)),
                ('rooms', models.IntegerField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.IntegerField(blank=True, default='', null=True)),
                ('approved', models.BooleanField()),
                ('sold', models.BooleanField()),
                ('onSaleDate', models.DateField()),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.City')),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
