# Generated by Django 2.2.1 on 2019-05-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('detached', 'Detached'), ('summer_house', 'Summer House'), ('stable', 'Stable'), ('Garage', 'Garage'), ('plot', 'Plot')], default='apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
