# Generated by Django 2.2.1 on 2019-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmentfeature_apartmentfeatureapartment_apartmenttype_apartmenttypeapartment_imageapartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentfeature',
            name='apartmentFeatureName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='apartmenttype',
            name='apartmentTypeName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
