# Generated by Django 2.2.1 on 2019-05-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20190507_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='owner',
            new_name='user',
        ),
    ]
