# Generated by Django 2.2.1 on 2019-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartmentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('town_house', 'Town House'), ('single_family', 'Single Family House'), ('detached', 'Detached'), ('summer_house', 'Summer House'), ('farm_house', 'Farm House'), ('stable', 'Stable'), ('garage', 'Garage'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('other', 'Other')], default='apartment', max_length=20),
        ),
    ]
