# Generated by Django 2.2.1 on 2019-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20190512_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo_main',
            field=models.ImageField(upload_to=''),
        ),
    ]
