# Generated by Django 2.2.1 on 2019-05-13 20:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_search_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo_main',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartmentimages',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
