# Generated by Django 2.2.1 on 2019-05-13 20:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_auto_20190513_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimages',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
