# Generated by Django 2.2.1 on 2019-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_auto_20190513_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo_main',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='apartmentimages',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
