# Generated by Django 2.2.1 on 2019-05-13 21:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_auto_20190513_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
