# Generated by Django 2.2.1 on 2019-05-13 21:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_auto_20190513_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo_main',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
