# Generated by Django 2.2.1 on 2019-05-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_apartment_features'),
        ('apartments', '0015_auto_20190513_2141'),
    ]

    operations = [
    ]
