# Generated by Django 2.2.1 on 2019-05-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_merge_20190513_2303'),
        ('apartments', '0016_merge_20190513_2301'),
    ]

    operations = [
    ]
