# Generated by Django 2.2.1 on 2019-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('imageURL', models.ImageField(blank=True, unique=True, upload_to='media/')),
                ('imageCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
