# Generated by Django 2.2.1 on 2019-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('imageURL', models.CharField(max_length=50)),
                ('imageCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
