# Generated by Django 2.2.1 on 2019-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=130)),
                ('city_postal_code', models.IntegerField(blank=True)),
                ('city_zip', models.IntegerField(blank=True)),
            ],
        ),
    ]
