# Generated by Django 2.2.1 on 2019-05-06 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20190506_2145'),
        ('image', '0002_auto_20190506_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='Male', max_length=5)),
                ('firstName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ssn', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('streetName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('streetNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('postalCode', models.IntegerField(blank=True, default=0, null=True)),
                ('creditCardNumber', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('creditCardSecurityNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('creditCardNameOnCard', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('creditCardExpiry', models.DateField(blank=True, null=True)),
                ('cityID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.City')),
                ('countryID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Country')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.UserProfile')),
            ],
        ),
    ]
