# Generated by Django 2.2.1 on 2019-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='Male', max_length=5),
        ),
    ]
