# Generated by Django 2.2.1 on 2019-05-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.UserProfile')),
            ],
        ),
    ]
