# Generated by Django 2.2.1 on 2019-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190507_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cityID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='countryID',
            new_name='country',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creditCardProvider',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
