# Generated by Django 2.2.1 on 2019-05-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20190507_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='creditCardNumber',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
    ]
