# Generated by Django 2.2.1 on 2019-05-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('ssn', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('street_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('street_number', models.IntegerField(blank=True, default=0, null=True)),
                ('postal_code', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(blank=True, default='', max_length=150, null=True, unique=True)),
                ('credit_card_provider', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_security_number', models.IntegerField(blank=True, default=0, null=True)),
                ('credit_card_name_on_card', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
