# Generated by Django 2.2.1 on 2019-05-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=15)),
                ('email', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('ssn', models.CharField(blank=True, default='', max_length=150, null=True, unique=True)),
                ('street_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('street_number', models.IntegerField(blank=True, default=0, null=True)),
                ('postal_code', models.IntegerField(blank=True, default=0, null=True)),
                ('credit_card_number', models.CharField(blank=True, default='', max_length=150, null=True, unique=True)),
                ('credit_card_provider', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_security_number', models.IntegerField(blank=True, default=0, null=True)),
                ('credit_card_name_on_card', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('city', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
