# Generated by Django 2.2.1 on 2019-05-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190511_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_main',
        ),
    ]
