# Generated by Django 2.2.1 on 2019-05-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='profile_image',
        ),
    ]
