# Generated by Django 2.2.1 on 2019-05-10 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20190509_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_card_expiry',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_card_name_on_card',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_card_provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit_card_security_number',
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(blank=True, default='', max_length=150, null=True, unique=True)),
                ('credit_card_provider', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_security_number', models.IntegerField(blank=True, default=0, null=True)),
                ('credit_card_name_on_card', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('credit_card_expiry', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
