# Generated by Django 2.2.1 on 2019-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190510_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
