# Generated by Django 2.2.1 on 2019-05-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190512_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
