# Generated by Django 2.2.1 on 2019-05-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190513_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
