# Generated by Django 2.2.1 on 2019-05-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
