# Generated by Django 2.2.1 on 2019-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190516_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditcard',
            name='credit_card_security_number',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
    ]
