# Generated by Django 2.2.1 on 2019-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
    ]
