# Generated by Django 2.2.1 on 2019-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190516_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditcard',
            name='credit_card_number',
            field=models.CharField(blank=True, default='', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercreditcard',
            name='credit_card_security_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
